exchange: bybit
spot: true
symbols: []  # empty means auto-universe from exchange

timeframe: 15m
lookback_bars: 400

universe:
  quote: USDT
  min_quote_volume_usd: 500000   # 24h volume threshold
  max_symbols: 30

risk:
  equity: 1000          # virtual equity for sizing if needed
  risk_pct: 1.0         # not used for DCA budget, but available
  atr_mult: 1.0

trading:
  per_order_usd: 5            # minimum per buy (USD/USDT)
  max_budget_per_symbol: 25   # total budget per symbol including DCA
  max_open_positions: 8
  dca_atr_steps: [0.5, 1.0, 1.5]   # add at entry - n*ATR
  trail_atr_mult: 2.0
  close_if_below_ema200: true
  use_market_orders: true
  poll_interval_sec: 60

telegram:
  enabled: true
  token_env: TELEGRAM_BOT_TOKEN
  chat_id_env: TELEGRAM_CHAT_ID

strategies:
  - pullback
  - breakout

fees:
  taker_bps: 10    # basis points per side (0.1%)
  maker_bps: 8